table 'Dim Product'
	lineageTag: 47b4d705-ea1a-4538-8eb7-2d57850a675a

	column Product
		dataType: string
		lineageTag: 28c46682-70f7-4897-afae-6fab53a287c4
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: e645e32d-9140-4999-a702-f05680abee13
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 08f3336a-544a-4895-84aa-b1fb2deeb394
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column CategoryID
		dataType: int64
		formatString: 0
		lineageTag: 452fae0d-a7d0-4874-b73c-6ee8c8ce8d4c
		summarizeBy: none
		sourceColumn: CategoryID

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 254f4df5-5a49-40a9-8e18-eb547f7cb615
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column SegmentID
		dataType: int64
		formatString: 0
		lineageTag: d198e6bd-6f77-4484-9fa5-5cbbbd6993cd
		summarizeBy: none
		sourceColumn: SegmentID

		annotation SummarizationSetBy = Automatic

	column 'Product Image'
		dataType: string
		lineageTag: b7c4ce4a-c2bc-4216-960a-33c9848b8d5d
		summarizeBy: none
		sourceColumn: Product Image

		annotation SummarizationSetBy = Automatic

	column 'Category Image'
		dataType: string
		lineageTag: 57977d66-bc39-4c21-9a37-f40f4d8ebb19
		summarizeBy: none
		sourceColumn: Category Image

		annotation SummarizationSetBy = Automatic

	column 'Segement Color'
		dataType: string
		lineageTag: 3daff8a7-0827-45d5-865c-b6b5f1349088
		summarizeBy: none
		sourceColumn: Segement Color

		annotation SummarizationSetBy = Automatic

	column 'Segment image'
		dataType: string
		lineageTag: bf79cebc-6ef4-433f-8173-7f92ae50baa5
		summarizeBy: none
		sourceColumn: Segment image

		annotation SummarizationSetBy = Automatic

	column Price
		dataType: int64
		formatString: 0
		lineageTag: 1f62bda9-3c8e-4185-8e30-c72b7ee88107
		summarizeBy: none
		sourceColumn: Price

		annotation SummarizationSetBy = Automatic

	column 'Price Range'
		dataType: string
		lineageTag: fd646dec-84ef-407e-a206-41974b4f5076
		summarizeBy: none
		sourceColumn: Price Range

		annotation SummarizationSetBy = Automatic

	partition 'Dim Product' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Sarvesh\OneDrive\Desktop\PBI Test Source Tables.xlsx"), null, true),
				    Product_Sheet = Source{[Item="Product",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Product_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Product", type text}, {"ProductID", Int64.Type}, {"Category", type text}, {"CategoryID", Int64.Type}, {"Segment", type text}, {"SegmentID", Int64.Type}, {"Product Image", type text}, {"Category Image", type text}, {"Segement Color", type text}, {"Segment image", type text}, {"Price", Int64.Type}, {"Price Range", type text}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

